"use client";

import { FormEvent, useEffect, useState } from "react";
import { additionalSkills, education, experiences, profile, projects, skillGroups, teachingSkills } from "@/lib/data";

const nav = ["About", "Skills", "Experience", "Projects", "Education", "Contact"];
function Section({ id, eyebrow, title, children }: { id: string; eyebrow: string; title: string; children: React.ReactNode }) { return <section id={id} className="section"><div className="section-head"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div>{children}</section>; }
function ThemeToggle() { const [dark, setDark] = useState(false); useEffect(() => { const next = localStorage.getItem("theme") === "dark"; setDark(next); document.documentElement.classList.toggle("dark", next); }, []); const toggle = () => { const next = !dark; setDark(next); document.documentElement.classList.toggle("dark", next); localStorage.setItem("theme", next ? "dark" : "light"); }; return <button className="icon-button" onClick={toggle} aria-label={dark ? "Switch to light theme" : "Switch to dark theme"} title={dark ? "Switch to light theme" : "Switch to dark theme"}>{dark ? "☼" : "☾"}</button>; }

export default function Home() {
  const [menu, setMenu] = useState(false); const [sent, setSent] = useState(false);
  const submit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setSent(true); event.currentTarget.reset(); };
  return <main>
    <nav className="nav"><a href="#home" className="brand">SUJAN<span>.</span></a><div id="primary-navigation" className={`nav-links ${menu ? "open" : ""}`}>{nav.map((item) => <a key={item} href={`#${item.toLowerCase()}`} onClick={() => setMenu(false)}>{item}</a>)}<a className="cv-link" href={profile.cv} download>Download CV</a></div><div className="nav-actions"><ThemeToggle /><button className="menu-button" onClick={() => setMenu(!menu)} aria-expanded={menu} aria-controls="primary-navigation" aria-label={menu ? "Close navigation menu" : "Open navigation menu"}>{menu ? "×" : "☰"}</button></div></nav>
    <section id="home" className="hero"><div className="hero-copy"><p className="eyebrow">HELLO, I&apos;M</p><h1>Sujan <em>Subedi</em></h1><p className="hero-title">Computer Teacher <span>/</span> Front-End Developer</p><p className="hero-summary">{profile.summary}</p><div className="hero-actions"><a className="button primary" href="#projects">View My Work <span>↗</span></a><a className="button secondary" href="#contact">Contact Me</a></div><div className="socials"><a href={profile.github} target="_blank" rel="noreferrer">GitHub ↗</a><a href={profile.linkedin} target="_blank" rel="noreferrer">LinkedIn ↗</a></div></div><div className="hero-art"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="profile-card"><div className="card-top"><span className="status-dot" /> Available for meaningful work</div><div className="monogram">SS</div><p className="card-name">{profile.name}</p><p>Computer Teacher</p><p>Front-End Developer</p><div className="card-location">⌖ {profile.location}</div></div></div></section>
    <Section id="about" eyebrow="01 / ABOUT" title="A teacher who builds." ><div className="about-grid"><p className="lead">{profile.about}</p><div className="mini-grid">{[["Teaching", "Practical computer science education."], ["Programming", "Python, JavaScript, TypeScript and React.js."], ["Web Development", "Responsive, user-friendly applications."]].map(([title, text]) => <article className="mini-card" key={title}><span>0{title === "Teaching" ? "1" : title === "Programming" ? "2" : "3"}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></Section>
    <Section id="skills" eyebrow="02 / CAPABILITIES" title="Tools I work with."><div className="skill-grid">{skillGroups.map((group) => <article className="skill-card" key={group.title}><h3>{group.title}</h3><div className="tag-list">{group.items.map((item) => <span key={item}>{item}</span>)}</div></article>)}</div></Section>
    <Section id="experience" eyebrow="03 / EXPERIENCE" title="Where I&apos;ve contributed."><div className="timeline">{experiences.map((item) => <article className="timeline-item" key={item.role + item.organization}><div className="timeline-marker" /><div><p className="period">{item.period}</p><h3>{item.role}</h3><p className="organization">{item.organization}{item.location && ` · ${item.location}`}</p><ul>{item.points.map((point) => <li key={point}>{point}</li>)}</ul></div></article>)}</div></Section>
    <Section id="projects" eyebrow="04 / SELECTED WORK" title="Projects with purpose."><div className="project-grid">{projects.map((project, index) => <article className="project-card" key={project.name}><div className="project-number">0{index + 1}</div><p className="period">{project.category}</p><h3>{project.name}</h3><p>{project.description}</p><div className="tag-list">{project.technologies.map((item) => <span key={item}>{item}</span>)}</div><ul>{project.features.map((feature) => <li key={feature}>{feature}</li>)}</ul></article>)}</div></Section>
    <Section id="education" eyebrow="05 / EDUCATION" title="The foundation."><div className="education-grid">{education.map((item) => <article className="education-card" key={item.degree}><span className="edu-mark">✦</span><p className="period">{item.short || "HIGHER SECONDARY EDUCATION"}</p><h3>{item.degree}</h3><p>{item.school}</p><p>{item.detail}</p></article>)}</div><div className="teaching-strip"><div><p className="eyebrow">TEACHING SKILLS</p><h3>Making technical ideas feel tangible.</h3></div><div className="tag-list">{teachingSkills.map((item) => <span key={item}>{item}</span>)}</div></div><div className="additional"><p className="eyebrow">ADDITIONAL SKILLS</p><div className="tag-list">{additionalSkills.map((item) => <span key={item}>{item}</span>)}</div></div></Section>
    <Section id="contact" eyebrow="06 / CONTACT" title="Let&apos;s work together."><div className="contact-grid"><div><p className="lead">Have a project, teaching opportunity, or collaboration in mind? Feel free to get in touch.</p><div className="contact-details"><a href={`mailto:${profile.email}`}><small>Email</small>{profile.email}</a><a href={`tel:${profile.phone}`}><small>Phone</small>{profile.phone}</a><p><small>Location</small>{profile.location}</p></div><div className="socials"><a href={`mailto:${profile.email}`}>Email Me ↗</a><a href={profile.github} target="_blank" rel="noreferrer">GitHub ↗</a><a href={profile.linkedin} target="_blank" rel="noreferrer">LinkedIn ↗</a></div></div><form className="contact-form" onSubmit={submit}><label htmlFor="contact-name">Name<input id="contact-name" name="name" autoComplete="name" required /></label><label htmlFor="contact-email">Email<input id="contact-email" type="email" name="email" autoComplete="email" required /></label><label htmlFor="contact-message">Message<textarea id="contact-message" name="message" rows={5} required /></label><button className="button primary" type="submit">{sent ? "Message validated" : "Send Message ↗"}</button>{sent && <p className="success" role="status">Thanks. Your message was validated locally. Please use Email Me to send it.</p>}</form></div></Section>
    <footer><a href="#home" className="brand">SUJAN<span>.</span></a><p>© 2026 Sujan Subedi. All rights reserved.</p><div className="socials"><a href={profile.github}>GitHub</a><a href={profile.linkedin}>LinkedIn</a><a href={`mailto:${profile.email}`}>Email</a></div></footer>
  </main>;
}
